### ISSUE TITLE
add() error

### ISSUE THREAD

**Issue by cristianodri** [Diademe/undo-redo-decorator#3]
Hello, I'm trying to use you Undo-Redo Decorator, but without success.

I've a class decorated with @Undoable(), but as soon as I use add() method, I get the following error:
ERROR Error: [object Object] is not decorated with @Undoable()
    at UndoRedo.internalAdd (index.js:31)

Here's my class:
```
import { GeoJsonObject } from 'geojson';
import { Undoable, UndoDoNotTrack } from 'undo-redo-decorator';
import { RouteStatus } from './routeStatus.enum';

@Undoable()
export class RouteDTO {
  id?: number;
  name: string;
  description?: string;
  route: GeoJsonObject;
  customId?: string;
  routeStatus?: RouteStatus;
  color?: string;

  constructor() {
    const colors = [
      '#00ffff',
      '#f0ffff',
     // ...
    ];
    if (this.color === '' || this.color === undefined || this.color === null) {
      this.color = colors[Math.floor(Math.random() * colors.length)];
    }
  }
}
```

GeoJsonObject is an interface and RouteStatus is an enum, so I can't decorate them.

In a second class I do:
```
ExampleClass{
    private ud = new UndoRedo();

    exampleMethod(){
        const route= //call method that returns a RouteDTO object
        this.ud.add(route);
    }
}
```

I've even tried adding UndoDoNotTrack to route and routeStatus members, but I continue getting the same error.
What is wrong with my code?

Best regards,
Cristiano

**Comment by Diademe** [comment]
Hello,
I can not reproduce the error with the code you gave: I tried to patch the missing piece (`const route= //call method that returns a RouteDTO object` with `const route = new RouteDTO()`), but it is working with my configuration.
My best guess is that the method that returns a RouteDTO doesn't.
Multiple possible reason:
- it returns an object not typed
  example: `const route = {name: "test", route = {type: "Point", bbox: [0, 0, 0, 0]}}`
- it returns a subclass of `RouteDTO` (this library require that the the last subclass must be decorated by `@Undoable()`)
- `RouteDTO` is decorated, [with another decorator that returns a value](https://www.typescriptlang.org/docs/handbook/decorators.html#class-decorators).

To confirm, do this test: 
```typescirpt
const route= //call method that returns a RouteDTO object
console.log(route.constructor === RouteDTO)
```
if it logs true, my guess is incorrect.
For further assistance, I need a complete code reproducing the error.

Remark: if `GeoJsonObject` is an interface, internal changes occurring inside it will not be tracked by the undo redo.

Regards

**Comment by cristianodri** [comment]
Hello @Diademe,

your guess is right, the method I call does not returns a RouteDTO, it returns an Object. 
Unfortunately I've no means to change this behavior so I'm out of luck in using your decorator. I'll continue following this project because I find it very interesting and I'm sure I'm going to put it to use sooner or later
